name: Build for Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -qq libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Build
        run: |
          make

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: car-linux.zip
          path: car.zip
