name: Build for Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install gcc-multilib
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

      - name: Build
        run: |
          make

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: car-linux.zip
          path: car.zip
