name: Build for Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\msys64.exe "{0}"
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain git

      - name: Build
        run: |
          make

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: car-windows.zip
          path: car.zip
